#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2012             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

# Check has been developed using an UPS Emerson/Liebert NX and General
# Electric NetPro 3000
#
# +------------------------------------------------------------------+
# | This file has been contributed by:                               |
# |                                                                  |
# | Václav Ovsík <vaclav.ovsik@gmail.com>             Copyright 2012 |
# +------------------------------------------------------------------+

# Example info:
#
#   [['230', '500', '230', '500', '80000', '10']]
#
#   [['230', '500', '230', '500', '3000', '2']]
#


def inventory_ups_config(info):
    if len(info) > 0:
        return [ (None, None) ]

def check_ups_config(item, params, info):
    InputVoltage, InputFreq, OutputVoltage, OutputFreq, OutputVA,\
        LowBattTime = [ saveint(x) for x in info[0] ]
    return (0, 'OK - '\
            + ('InputVoltage: %dV, ' % InputVoltage)\
            + ('InputFreq: %d.%dHz, ' % divmod(InputFreq, 10))\
            + ('OutputVoltage: %dV, ' % OutputVoltage)\
            + ('OutputFreq: %d.%dHz, ' % divmod(OutputFreq, 10))\
            + ('OutputVA: %dVA, ' % OutputVA) \
            + ('LowBattTime: %dmin' % LowBattTime) 
            )

check_info['ups_config'] = (check_ups_config, 'UPS Config',
        0, inventory_ups_config)

snmp_info['ups_config'] = ('.1.3.6.1.2.1.33.1.9', [
        '1.0',  # UPS-MIB::upsConfigInputVoltage.0
        '2.0',  # UPS-MIB::upsConfigInputFreq.0
        '3.0',  # UPS-MIB::upsConfigOutputVoltage.0
        '4.0',  # UPS-MIB::upsConfigOutputFreq.0
        '5.0',  # UPS-MIB::upsConfigOutputVA.0
        '7.0',  # UPS-MIB::upsConfigLowBattTime.0
    ])

snmp_scan_functions['ups_config'] = \
     lambda oid: oid('.1.3.6.1.2.1.33.1.9.1.0') != None

