#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2012             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

# Check has been developed using an UPS Emerson/Liebert NX and General
# Electric NetPro 3000
#
# +------------------------------------------------------------------+
# | This file has been contributed by:                               |
# |                                                                  |
# | Václav Ovsík <vaclav.ovsik@gmail.com>             Copyright 2012 |
# +------------------------------------------------------------------+

# Example info:
#
#   [['1']]
#

# The right value for check's OK state
ups_autorestart_default_param = 1


def inventory_ups_autorestart(info):
    if len(info) == 0:
        return
    return [ (None, 'ups_autorestart_default_param') ]

def check_ups_autorestart(item, params, info):
    auto = saveint(info[0][0])
    chkval = params
    if auto != chkval:
        status = 2
        stxt = 'CRIT'
    else:
        status = 0
        stxt = 'OK'
    return (status, stxt + ' - Autorestart: ' \
             + { 1:'on(1)', 2:'off(2)' }[auto])

check_info['ups_autorestart'] = \
        (check_ups_autorestart, 'UPS Autorestart', 0, inventory_ups_autorestart)

snmp_info['ups_autorestart'] = \
        ('.1.3.6.1.2.1.33.1.8', ['5.0']) # UPS-MIB::upsAutoRestart.0

snmp_scan_functions['ups_autorestart'] = \
        lambda oid: oid('.1.3.6.1.2.1.33.1.8.5.0')

