#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2012             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

# Check has been developed using an UPS Emerson/Liebert NX and General
# Electric NetPro 3000
#
# +------------------------------------------------------------------+
# | This file has been contributed by:                               |
# |                                                                  |
# | Václav Ovsík <vaclav.ovsik@gmail.com>             Copyright 2012 |
# +------------------------------------------------------------------+

# Example info:
#
#   [['Liebert Corporation', 'Liebert NX', 'I190R200M270', '3.310.2']]
#
#   [['GE', 'NetPro 3000', 'V8;0861-B0;0862-', 'v4.0']]
#


def inventory_ups_ident(info):
    if len(info) > 0:
        return [ (None, None) ]

def check_ups_ident(item, params, info):
    ident, = info
    if len(ident) < 4:
        return (3, "UNKNOWN - No data retrieved")
    return (0, 'OK - Manufacturer: %s, Model: %s, UPS Software '
            'Version: %s, Agent Software Version: %s' % tuple(ident))


check_info['ups_ident'] = (check_ups_ident, 'UPS Ident',
        0, inventory_ups_ident)

snmp_info['ups_ident'] = ('.1.3.6.1.2.1.33.1.1', [
        '1.0',  # UPS-MIB::upsIdentManufacturer.0
	    '2.0',  # UPS-MIB::upsIdentModel.0
        '3.0',  # UPS-MIB::upsIdentUPSSoftwareVersion.0
        '4.0',  # UPS-MIB::upsIdentAgentSoftwareVersion.0
    ])

snmp_scan_functions['ups_ident'] = \
        lambda oid: oid('.1.3.6.1.2.1.33.1.1.2.0')

